"""Add InsurancePolicy

Revision ID: fb4da938e8f7
Revises: 03d9678fc68d
Create Date: 2026-08-15 18:50:04.902626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4da938e8f7'
down_revision: Union[str, Sequence[str], None] = '03d9678fc68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('premium_amount', sa.Float(), nullable=True),
    sa.Column('coverage_amount', sa.Float(), nullable=True),
    sa.Column('canonical_hash', sa.String(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='policystatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_policies')
    # ### end Alembic commands ###
